### ISSUE TITLE
Incosistent naming

### ISSUE THREAD

**Issue by umpirsky** [akovalyov/facebook-desktop#8]
Using different name in software center, launcher, app window.

![screenshot from 2015-11-02 11 39 00](https://cloud.githubusercontent.com/assets/208957/10879772/6a5d72c0-8156-11e5-8bb9-633c9cfc033e.png)
![ubuntu software center_013](https://cloud.githubusercontent.com/assets/208957/10879770/6a5b3276-8156-11e5-8950-6672035ef12b.png)
![selection_015](https://cloud.githubusercontent.com/assets/208957/10879792/871c4788-8156-11e5-9486-699991499ae9.png)

**Comment by akovalyov** [comment]
@umpirsky https://github.com/akovalyov/facebook-desktop/releases/tag/v0.0.1-alpha.2 released with the fix.
